export default [{
  username: 'viczam',
  firstName: 'Victor',
  lastName: 'Zamfir',
  email: 'victor@wirestorm.us',
  password: 'vm_p4ss',
  role: 'admin',
  address: {
    streetAddress1: '123 Abcde Ln.',
    city: 'Jeff',
    state: 'PA',
    zipCode: '12345',
    phoneNumber: '1234567890',
  },
}, {
  username: 'orcatalin',
  firstName: 'Catalin',
  lastName: 'Obreja',
  email: 'catalin@wirestorm.us',
  password: 'on_p4ss',
  role: 'admin',
  address: {
    streetAddress1: '123 Abcde Ln.',
    city: 'Jeff',
    state: 'PA',
    zipCode: '12345',
    phoneNumber: '1234567890',
  },
}, {
  username: 'gerryfudd',
  firstName: 'David',
  lastName: 'Hasenjaeger',
  email: 'david@wirestorm.us',
  password: 'gd_p4ss',
  role: 'admin',
  address: {
    streetAddress1: '123 Abcde Ln.',
    city: 'Jeff',
    state: 'PA',
    zipCode: '12345',
    phoneNumber: '1234567890',
  },
}];
